accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

articles/urls.py
from django.urls import path

from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleCreateView,  # new
)

urlpatterns = [
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("new/", ArticleCreateView.as_view(), name="article_new"),  # new
    path("", ArticleListView.as_view(), name="article_list"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),  # new
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path

from .views import HomePageView
from .views import GardenPageView
from .views import IdPageView
from .views import ArticlePageView


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("garden", GardenPageView.as_view(), name="garden"),
    path("id", IdPageView.as_view(), name="id"),
    path("article", ArticlePageView.as_view(), name="article"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})


class Comment(models.Model):  # new
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )  # new


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )  # new

articles/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View  # new
from django.views.generic import ListView, DetailView, FormView  # new
from django.views.generic.detail import SingleObjectMixin  # new
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy
from django.urls import reverse_lazy, reverse  # new

from .forms import CommentForm
from .models import Article


class CommentGet(DetailView):  # new
    model = Article
    template_name = "article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):  # new
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.object
        return reverse("article_detail", kwargs={"pk": article.pk})


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "article_list.html"


class ArticleDetailView(LoginRequiredMixin, View):  # new
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = (
        "title",
        "body",
    )
    template_name = "article_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = "article_delete.html"
    success_url = reverse_lazy("article_list")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "article_new.html"
    fields = ("title", "body")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class GardenPageView(TemplateView):
    template_name = "garden.html"


class IdPageView(TemplateView):
    template_name = "id.html"


class ArticlePageView(TemplateView):
    template_name = "article_list.html"

templates/article_delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Articles{% endblock title %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ article.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>




{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Articles{% endblock title %}

{% block content %}
<div class="article-entry">
    <h2>{{ object.title }}</h2>
    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
</div>
<hr>
<h4>Comments</h4>
{% for comment in article.comment_set.all %}
<p>{{ comment.author }} &middot; {{ comment }}</p>
{% endfor %}
<hr>
<h4>Add a comment</h4>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
<div>
    {% if article.author.pk == request.user.pk %}
    <p><a href="{% url 'article_edit' article.pk %}">Edit</a>
        <a href="{% url 'article_delete' article.pk %}">Delete</a>
    </p>
    {% endif %}
    <p>Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>
</div>


{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Articles{% endblock title %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>



{% endblock content %}

templates/article_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Articles{% endblock title %}

{% block content %}
{% for article in article_list %}
<div class="card">
    <div class="card-header">
        <span class="fw-bold">
            <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
        </span> &middot;
        <span class="text-muted">by {{ article.author }} |
            {{ article.date }}</span>
    </div>
    <div class="card-body">
        {{ article.body }}
        {% if article.author.pk == request.user.pk %}

        {% endif %}
    </div>


    <div class="card-footer">
        {% for comment in article.comment_set.all %}
        <p>
            <span class="fw-bold">
                {{ comment.author }} &middot;
            </span>
            {{ comment }}
        </p>
        {% endfor %}
    </div>
</div>
<div class="card-footer text-center text-muted">
    {% if article.author.pk == request.user.pk %}
    <a href="{% url 'article_edit' article.pk %}">Edit</a>
    <a href="{% url 'article_delete' article.pk %}">Delete</a>
    {% endif %}
    <a href="{{ article.get_absolute_url }}">New Comment</a>
</div>
<br />





{% endfor %}
{% endblock content %}

templates/article_new.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Articles{% endblock title %}

{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>



{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{% block title %}Gardening App{% endblock title %}</title>
    <meta name="viewport" content="width=device-width,
  initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>



<body>



    </style>

    <!--Header-->
    <header class="p-3 mb-3 border-bottom">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand size" href="#"> <i class="bi bi-flower1"></i>
                    Green Thumb Guidance | </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'garden' %}">Lets Grow Something</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'id' %}">Oh, what can we grow</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'article_list' %}">Lets Talk Plants</a>
                        </li>




                        {% if user.is_authenticated %}
                        <li><a href="{% url 'article_new' %}" class="nav-link px-2 link-dark">+ New</a></li>
                    </ul>
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                            data-bs-toggle="dropdown" aria-expanded="false">

                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{% url 'password_change' %}">
                                    Change password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                        </ul>
                    </div>

                    {% else %}
                    </ul>
                    <div class="text-end">
                        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
                            Log In</a>
                        <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </nav>
        </div>
        </div>
    </header>





    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>




    <!--Footer  class="navbar-fixed-bottom"
    <footer class=" nav-bar-fixed-bottom p-5 text-white text-center position-relative text-center"
        style="background-color: #054d3b;">
        <div class="container">
            <p class="lead">Copyright &copy; 2023 Blooming Beauties</p>
        </div>

        footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 160px;
}
    </footer>-->


    <footer class="bg-info text-center text-lg-start  position-relative">
        <div class="text-center p-3 text text-white" style="background-color: #054d3b">
            © 2023 Copyright:
            <a class="text-white">Green Thumb Guidance</a>
        </div>
        <!-- Copyright -->
    </footer>


    <!-- Bootstrap JavaScript Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>

</body>

</html>

templates/garden.html
{% extends "base.html" %}

{% block title %}Garden{% endblock title %}

{% block content %}
{% if user.is_authenticated %}
Hi {{ user.username }}! You are {{ user.age }} years old.
<p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}




{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="style.css">
    <title>Blooming Beauties</title>
</head>








<!--Showcase-->
<section class="bg-light text-dark p-5 p-lg-1text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex">
            <div>
                <h1> Gardening <span class="text" style="color:#054d3b"></span>
                </h1>
                <p class="lead my-4">Gardening is about finding the right combination of sunlight, fertile soil, and
                    water to make your plants thrive.
                    It's also about fulfilling your passion, so select plants you love. Use the resources here as a
                    starting point, and
                    in no time you’ll have a beautiful garden, no matter what level of gardening experience you have.

                    Beyond the beauty it
                    brings to outdoor spaces, gardening provides a deep sense of connection to nature and a soothing
                    escape
                    from the hustle of daily life. It promotes physical activity and mental well-being, as tending to
                    plants
                    and watching them thrive can be immensely satisfying. Cultivating a garden also allows individuals
                    to
                    grow their own fresh, organic produce, contributing to healthier diets and a reduced carbon
                    footprint.
                    Moreover, gardens create habitats for pollinators and other wildlife, fostering biodiversity.
                </p>
            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'images/gardenimage.webp' %}" alt="" />
        </div>
    </div>
</section>



<!--Showcase-->
<section class="bg-light text-dark p-5 p-lg-1 text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex">
            <div>
                <h1>The Basics<span class="text" style="color:#054d3b"></span></h1>
                <p class="lead my-4">
                    Beginning gardeners are often intimidated by the process of how to start a garden and care for
                    it successfully—after all, there's a lot involved. From amending your soil with high-quality
                    organic matter to pruning shrubs, you'll find answers and advice for essential gardening tasks.
                    Here are some steps you will want to take to start your own garden:
                <ol>
                    <li>Choose the Right Location: Find a sunny area with good drainage for your garden.</li>
                    <li>Prepare the Soil: Test the soil and amend it with compost to improve fertility and structure.
                    </li>
                    <li>Select Your Plants: Choose plants that match your climate, soil type, and gardening goals.</li>
                    <li>Plan the Layout: Decide on the arrangement and spacing of plants based on their growth habits.
                    </li>
                    <li>Planting: Plant seeds or young plants according to recommended depths and distances.</li>
                    <li>Provide Adequate Water: Water consistently, giving plants enough moisture without overwatering.
                    </li>
                    <li>Mulch for Protection: Apply mulch to retain moisture, prevent weeds, and regulate soil
                        temperature.</li>
                    <li>Monitor and Care: Keep an eye on plant growth, address pest or disease issues promptly, and
                        adjust care as needed.</li>
                </ol>
                </p>
            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'images/gardentools.jpg' %}" alt="" />
        </div>
    </div>
</section>




<!--Showcase-->
<section class="bg-light text-dark p-5 p-lg-1text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex">
            <div>
                <h1> Watering your garden <span class="text" style="color:#054d3b"></span></h1>
                <p class="lead my-4">Watering a garden is a critical practice that requires a delicate balance.
                    Providing plants with the right amount of water at the appropriate times is essential for their
                    growth and
                    well-being. Regular watering, typically early in the morning or late in the afternoon, helps plants
                    absorb
                    moisture efficiently and reduces the risk of evaporation. It's important to water deeply, allowing
                    the
                    soil to be thoroughly moistened, which encourages plants to develop deep root systems. However,
                    overwatering should be avoided, as it can lead to root rot and other issues. Factors like weather
                    conditions, plant types, and soil type influence the frequency and amount of water needed. By paying
                    attention
                    to the specific needs of each plant and adapting
                    watering practices accordingly, gardeners can foster healthy, vibrant growth throughout their
                    garden.
                </p>
            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'images/wateringcan.webp' %}" alt="" />
        </div>
    </div>
</section>



<!--Showcase-->
<section class="bg-light text-dark p-5 p-lg-1text-center text-sm-start">
    <div class="container">
        <div class="d-sm-flex">
            <div>
                <h1> Soil recipes <span class="text" style="color:#054d3b"></span></h1>
                <p class="lead my-4">
                <h3>1. General Garden Soil Mix:</h3>
                <ul>
                    <li>40% garden soil or topsoil</li>
                    <li>40% compost (to improve soil structure and fertility)</li>
                    <li>20% perlite or vermiculite (for improved drainage and aeration)</li>
                </ul>

                <h3>2. Container Garden Mix:</h3>
                <ul>
                    <li>40% potting mix or compost</li>
                    <li>30% peat moss or coconut coir (to retain moisture)</li>
                    <li>30% perlite or vermiculite (for drainage and aeration)</li>
                </ul>

                <h3>3. Raised Bed Garden Mix:</h3>
                <ul>
                    <li>40% garden soil or topsoil</li>
                    <li>30% compost</li>
                    <li>20% aged manure (to enrich soil with nutrients)</li>
                    <li>10% perlite or vermiculite (for aeration)</li>
                </ul>

                <h3>4. Seed Starting Mix:</h3>
                <ul>
                    <li>50% peat moss or coconut coir</li>
                    <li>30% perlite or vermiculite</li>
                    <li>20% compost (sterilized, to provide nutrients)</li>
                </ul>
                </p>
                </p>
            </div>
            <img class="img-fluid w-50 d-none d-sm-block" src="{% static 'images/shovel.png' %}" alt="" />
        </div>
    </div>
</section>






<!--Question Accordiom-->
<section id="questions" class="p-5">
    <div class="container">
        <h2 class="text-center mb-4"> Frequently asked Questions
        </h2>
        <div class="accordion accordion-flush" id="Questions">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#question-one" aria-expanded="false" aria-controls="flush-collapseOne">
                        When should I start planting my garden?
                    </button>
                </h2>
                <div id="question-one" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                    data-bs-parent="#Questions">
                    <div class="accordion-body">The timing of planting varies based on your location and the types of
                        plants you're growing.
                        In general, start seeds indoors a few weeks before the last frost date, and for outdoor
                        planting,
                        follow the recommended planting dates for your region.
                    </div>
                </div>
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#question-one" aria-expanded="false" aria-controls="flush-collapseOne">
                            What's the difference between compost and fertilizer?
                        </button>
                    </h2>
                    <div id="question-one" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                        data-bs-parent="#Questions">
                        <div class="accordion-body">Compost is a mixture of organic materials that improves soil
                            structure and provides nutrients over time.
                            Fertilizer is a concentrated nutrient source that's applied to plants to promote growth.
                            Compost improves soil health, while fertilizer provides specific nutrients.
                        </div>
                    </div>
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#question-one" aria-expanded="false" aria-controls="flush-collapseOne">
                                How can I deal with garden pests?
                            </button>
                        </h2>
                        <div id="question-one" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                            data-bs-parent="#Questions">
                            <div class="accordion-body">Integrated Pest Management (IPM) involves using a combination of
                                methods such as physical barriers,
                                beneficial insects, companion planting, and selective pesticide use to manage pests
                                while minimizing harm to beneficial organisms and the environment.
                            </div>
                        </div>
                    </div>
</section>

</body>

</html>




{% endif %}
{% endblock content %}